### ISSUE TITLE
Revisión de límites de caracteres en base de datos y propiedades de modelos

### ISSUE THREAD

**Issue by raraya95** [Funread/funread#303]
Los cuadros de texto en la aplicación no tienen límite. Esto debe ser aplicado para todos los campos que permiten caracteres en si.

Criterio de aceptación:
1. Todos las propiedades de los modelos deben manejar un límite de caracteres idóneo.
2. Estos límites deben estar especificados tanto en los modelos como en la base de datos (migración)
3. Trabajar en conjunto con FE para que los mismos límites se apliquen en los componentes

**Comment by Jose-AB4rca** [comment]
@raraya95 Y @Lenar-Tercero en el drive subí la revisión de los paramtetros de los modelos y la DB con algunas ideas para realizar cambios, si les parece bien me hago una rama y los aplico allí pero si necesasitaria una respuesta rapida, si consideran que debo hablar con alguien de FE sería bueno si me indican con quien.

**Comment by raraya95** [comment]
@Jose-AB4rca, el punto 2 del issue dice que se debe hacer los cambios en caso de que se haya agregado nuevos o modificado existentes.
Con respecto a lo de FE, puedes hablar con @Kevingonz que es el lead de FE para que le compartas el documento con los límites y ellos puedan crear un issue para que se realicen las modificaciones en el código del FE

**Comment by Jose-AB4rca** [comment]
@raraya95  La documentación ya se la pasé a Francisco (otro de los leads de FE) y le comenté lo que hay que hacer, también que se lo comparta a Kevin.

El punto 2 del issue dice esto
2) Estos límites deben estar especificados tanto en los modelos como en la base de datos (migración)

A3hi si no te entiendí bien que quieras decir, pero tanto la documentación como la comunicación con FE ya se realizaron, tambien unos pequeños cambios en un par de modelos que consideré razonable pero solo para que tengan el mismo tamaño entre tablas los atributos de email.

**Comment by raraya95** [comment]
@Jose-AB4rca perfecto, no había visto el PR, ya me pongo con eso
