### ISSUE TITLE
Revisar consulta eliminar libros por clase

### ISSUE THREAD

**Issue by raraya95** [Funread/funread#306]
Actualmente no se puede eliminar libros de una clase. Esta funcionalidad debe permitirse

Criterio de aceptación
1. Revisar si existe el procedimiento en el backend para eliminar libros de una clase. Si no existe, crearlo. Si existe, verificar si el funcionamiento está roto debido a falta de comunicación en FE y BE o bien un problema del procedimiento como tal.
2. Verificar si existe opción de eliminar
3. Revisar con postman

![Image](https://github.com/user-attachments/assets/db647524-e3a6-4b74-8805-f1dab15c5b2c)

**Comment by DeynerPR** [comment]
EL método para eliminar libros de una clase no está siendo utilizado/llamado en el front end.

Se probó con postman la correcta funcionalidad del método en backend (modifica el atributo del registro "isactive" de 1 a 0).

[Prueba con Postman del método para eliminar libro de una clase..pdf](https://github.com/user-attachments/files/17305213/Prueba.con.Postman.del.metodo.para.eliminar.libro.de.una.clase.pdf)

**Comment by raraya95** [comment]
@DeynerPR muchas gracias por la revisión, buen trabajo.

@Kevingonz por favor revisar y agregar ticket a backlog FE (si no existe), para agregar la funcionalidad de eliminar libros desde el FE. Como menciona Deyner, el BE tiene el endpoint funcional para eliminar libros, simplemente no se está llamando
