### ISSUE TITLE
[Gamificación] - Implementar y crear estructura de tablas puntos, recompensas y badges

### ISSUE THREAD

**Issue by raraya95** [Funread/funread#322]
Gamificación es la habilidad de otorgar reconocimientos a los alumnos/usuarios por medio de juegos y actividades para incentivar el estudio y la incorporación a tareas de la plataforma

ACs
- Una vez aceptada la propuesta del diagrama de tablas, se debe crear la estructura en la base de datos

**Comment by raraya95** [comment]
[ejemplos_gamificacion.pdf](https://github.com/user-attachments/files/17368437/ejemplos_gamificacion.pdf)

Acá se tiene la documentación sobre lo que se requiere y ciertos ejemplos

**Comment by raraya95** [comment]
@tonymj23 @Gerardoprogramer veo que movieron el ticket a CR pero no veo un PR asociado, me cuentan cualquier cosa

**Comment by tonymj23** [comment]
@raraya95 mala mía, pensé que lo había hecho.

**Comment by tonymj23** [comment]
Ticket passed to QA.
