### ISSUE TITLE
[Gamificación] - Crear endpoints puntos, recompensas y badges

### ISSUE THREAD

**Issue by raraya95** [Funread/funread#324]
Gamificación es la habilidad de otorgar reconocimientos a los alumnos/usuarios por medio de juegos y actividades para incentivar el estudio y la incorporación a tareas de la plataforma

ACs
- Se debe crear endpoints para permitir agregar, editar, consultar los puntos y badges de los alumnos

**Comment by raraya95** [comment]
[ejemplos_gamificacion.pdf](https://github.com/user-attachments/files/17368438/ejemplos_gamificacion.pdf)

Acá se tiene la documentación sobre lo que se requiere y ciertos ejemplos

**Comment by DarvinGuti13** [comment]
@raraya95 @Lenar-Tercero Listo este Ticket para revisar!!
